version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html:delegated
#      - ./docker/php-fpm/local/php.ini:/usr/local/etc/php/php.ini:delegated
#      - ./docker/php-fpm/local/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    networks:
      - default