version: '3'
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Docker/php-fpm/Dockerfile
    volumes:
      - .:/var/www/html:delegated
    networks:
      - default
  chrome:
    build:
      context: .
      dockerfile: ./Docker/chrome/Dockerfile
    volumes:
      - .:/var/www/html:delegated
    networks:
      - default
volumes:
  storage: